export const examples = [
  {
    id: 'welcome',
    name: 'Welcome Card',
    template:
      '# {{project.name}}\n\n{{#features}}- {{.}}\n{{/features}}\n{{> footer}}',
    contextJson: JSON.stringify(
      {
        project: { name: 'moon-mustache' },
        features: ['CLI rendering', 'Official spec coverage', 'Bundle planning'],
      },
      null,
      2,
    ),
    partialsJson: JSON.stringify(
      {
        footer: 'Generated by {{project.name}}.',
      },
      null,
      2,
    ),
  },
  {
    id: 'email',
    name: 'Release Email',
    template:
      'Subject: {{release.name}} is live\n\nHello {{user.name}},\n\n{{#highlights}}- {{.}}\n{{/highlights}}\n{{^highlights}}- No highlights provided\n{{/highlights}}\n\n{{> signature}}',
    contextJson: JSON.stringify(
      {
        release: { name: 'Moon Mustache 0.2.0' },
        user: { name: 'maintainer' },
        highlights: ['Official fixture parity', 'CLI diagnostics', 'Vue playground'],
      },
      null,
      2,
    ),
    partialsJson: JSON.stringify(
      {
        signature: 'Regards,\nMoonBit tooling team',
      },
      null,
      2,
    ),
  },
  {
    id: 'missing',
    name: 'Missing Variable Demo',
    template: 'Hello {{user.name}}, deploy target is {{target}}.',
    contextJson: JSON.stringify(
      {
        user: { name: 'operator' },
      },
      null,
      2,
    ),
    partialsJson: '{}',
  },
  {
    id: 'invalid-json',
    name: 'Invalid JSON Diagnostic',
    template: 'Release {{release.name}} is ready.',
    contextJson: '{\n  "release": { "name": "0.2.0" }',
    partialsJson: '{}',
  },
]
