from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def moon_command() -> str:
    for candidate in ("moon", "moon.exe", "moon.cmd"):
        found = shutil.which(candidate)
        if found:
            return found
    raise RuntimeError("MoonBit executable `moon` was not found on PATH")


def run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [moon_command(), "run", "--target", "js", "cli", *args],
        cwd=ROOT,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=False,
    )


def expect(condition: bool, message: str, result: subprocess.CompletedProcess[str]) -> None:
    if condition:
        return
    raise AssertionError(
        f"{message}\nexit={result.returncode}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def case(name: str, test) -> dict[str, object]:
    started = time.perf_counter()
    test()
    return {"name": name, "status": "passed", "duration_ms": round((time.perf_counter() - started) * 1000)}


def test_inline_render() -> None:
    result = run_cli("--template", "Hello {{name}}", "--var", "name=MoonBit")
    expect(result.returncode == 0, "inline render should succeed", result)
    expect(result.stdout.strip() == "Hello MoonBit", "inline output changed", result)


def test_file_render() -> None:
    result = run_cli(
        "--template-file",
        "examples/files/template.mustache",
        "--json-file",
        "examples/files/context.json",
        "--partials-json-file",
        "examples/files/partials.json",
    )
    expect(result.returncode == 0, "file-backed render should succeed", result)
    expected_lines = [
        "- Alice <alice@example.com>",
        "- Bob <bob@example.com>",
        "Generated by Moon Mustache.",
    ]
    for line in expected_lines:
        expect(line in result.stdout, f"file-backed output is missing {line!r}", result)


def test_strict_failure_exit_code() -> None:
    result = run_cli(
        "--template",
        "Hello {{missing}}",
        "--strict-missing",
        "--strict",
    )
    expect(result.returncode != 0, "strict diagnostics must return a non-zero exit code", result)
    expect("missing variable: missing" in result.stdout, "missing-variable diagnostic disappeared", result)
    expect("No rendered output was produced" in result.stdout, "strict mode should explain why output was blocked", result)


def test_lint_failure_exit_code() -> None:
    result = run_cli("--template", "{{#open}}", "--lint")
    expect(result.returncode != 0, "lint errors must return a non-zero exit code", result)
    expect("MST-PARSE-003" in result.stdout, "stable parse diagnostic code disappeared", result)


def test_bundle_generation() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-") as directory:
        output = Path(directory)
        result = run_cli(
            "--bundle-manifest-file",
            "examples/bundle/manifest.json",
            "--bundle-profile",
            "dev",
            "--json-file",
            "examples/bundle/context.json",
            "--bundle-output-dir",
            str(output),
            "--bundle-validation-file",
            str(output / "validation.md"),
            "--bundle-plan-file",
            str(output / "plan.md"),
        )
        expect(result.returncode == 0, "bundle generation should succeed", result)
        expected_files = [
            output / ".env",
            output / "README.generated.md",
            output / "deploy" / "config.toml",
            output / "validation.md",
            output / "plan.md",
        ]
        for path in expected_files:
            expect(path.is_file(), f"bundle output was not created: {path.name}", result)
        expect("APP_PORT=3000" in (output / ".env").read_text(encoding="utf-8"), "dev profile was not applied", result)
        expect("validation errors: 0" in (output / "plan.md").read_text(encoding="utf-8"), "plan is not clean", result)


def main() -> int:
    parser = argparse.ArgumentParser(description="Black-box integration tests for the Moon Mustache CLI")
    parser.add_argument("--json-output", type=Path, help="optional path for a machine-readable result")
    args = parser.parse_args()

    tests = [
        ("inline render", test_inline_render),
        ("file-backed render", test_file_render),
        ("strict failure exit code", test_strict_failure_exit_code),
        ("lint failure exit code", test_lint_failure_exit_code),
        ("bundle generation", test_bundle_generation),
    ]
    results: list[dict[str, object]] = []
    try:
        for name, test in tests:
            result = case(name, test)
            results.append(result)
            print(f"PASS  {name} ({result['duration_ms']} ms)")
    except Exception as error:
        results.append({"name": name, "status": "failed", "error": str(error)})
        print(f"FAIL  {name}\n{error}", file=sys.stderr)
        status = 1
    else:
        status = 0

    payload = {
        "suite": "moon-mustache CLI integration",
        "passed": sum(item["status"] == "passed" for item in results),
        "total": len(tests),
        "cases": results,
    }
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"CLI integration: {payload['passed']} / {payload['total']} passed")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
