from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def moon_command() -> str:
    for candidate in ("moon", "moon.exe", "moon.cmd"):
        found = shutil.which(candidate)
        if found:
            return found
    raise RuntimeError("MoonBit executable `moon` was not found on PATH")


def run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [moon_command(), "run", "--target", "js", "cli", *args],
        cwd=ROOT,
        text=True,
        encoding="utf-8",
        capture_output=True,
        check=False,
    )


def expect(condition: bool, message: str, result: subprocess.CompletedProcess[str]) -> None:
    if condition:
        return
    raise AssertionError(
        f"{message}\nexit={result.returncode}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def case(name: str, test) -> dict[str, object]:
    started = time.perf_counter()
    test()
    return {"name": name, "status": "passed", "duration_ms": round((time.perf_counter() - started) * 1000)}


def test_inline_render() -> None:
    result = run_cli("--template", "Hello {{name}}", "--var", "name=MoonBit")
    expect(result.returncode == 0, "inline render should succeed", result)
    expect(result.stdout.strip() == "Hello MoonBit", "inline output changed", result)


def test_file_render() -> None:
    result = run_cli(
        "--template-file",
        "examples/files/template.mustache",
        "--json-file",
        "examples/files/context.json",
        "--partials-json-file",
        "examples/files/partials.json",
    )
    expect(result.returncode == 0, "file-backed render should succeed", result)
    expected_lines = [
        "- Alice <alice@example.com>",
        "- Bob <bob@example.com>",
        "Generated by Moon Mustache.",
    ]
    for line in expected_lines:
        expect(line in result.stdout, f"file-backed output is missing {line!r}", result)


def test_output_file() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-output-") as directory:
        output = Path(directory) / "rendered.txt"
        result = run_cli(
            "--template",
            "Hello {{name}}",
            "--var",
            "name=MoonBit",
            "--output",
            str(output),
        )
        expect(result.returncode == 0, "output-file render should succeed", result)
        expect(output.read_text(encoding="utf-8") == "Hello MoonBit", "output file content changed", result)


def test_strict_failure_exit_code() -> None:
    result = run_cli(
        "--template",
        "Hello {{missing}}",
        "--strict-missing",
        "--strict",
    )
    expect(result.returncode != 0, "strict diagnostics must return a non-zero exit code", result)
    expect("missing variable: missing" in result.stdout, "missing-variable diagnostic disappeared", result)
    expect("No rendered output was produced" in result.stdout, "strict mode should explain why output was blocked", result)


def test_invalid_json_exit_code() -> None:
    result = run_cli(
        "--template",
        "Hello {{name}}",
        "--json",
        "{broken",
        "--strict",
    )
    expect(result.returncode != 0, "invalid JSON must return a non-zero exit code", result)
    expect("invalid JSON context" in result.stdout, "invalid-JSON diagnostic disappeared", result)


def test_missing_partial_exit_code() -> None:
    result = run_cli("--template", "{{> missing}}", "--strict")
    expect(result.returncode != 0, "missing partial must return a non-zero exit code", result)
    expect("missing partial: missing" in result.stdout, "missing-partial diagnostic disappeared", result)


def test_missing_input_file_exit_code() -> None:
    result = run_cli(
        "--template-file",
        "examples/files/does-not-exist.mustache",
    )
    expect(result.returncode != 0, "missing template file must return a non-zero exit code", result)
    expect("failed to read template file" in result.stdout, "missing-file diagnostic disappeared", result)


def test_invalid_bundle_manifest_exit_code() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-invalid-manifest-") as directory:
        manifest = Path(directory) / "manifest.json"
        manifest.write_text("{broken", encoding="utf-8")
        result = run_cli("--bundle-manifest-file", str(manifest))
        expect(result.returncode != 0, "invalid bundle manifest must return a non-zero exit code", result)
        expect("invalid bundle manifest" in result.stdout, "manifest diagnostic disappeared", result)


def test_unsupported_bundle_report_format_exit_code() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-report-format-") as directory:
        root = Path(directory)
        manifest = write_manifest(root, [{"path": "README.md", "template": "# report"}])
        report = root / "report.txt"
        result = run_cli(
            "--bundle-manifest-file",
            str(manifest),
            "--bundle-report-file",
            str(report),
            "--bundle-report-format",
            "yaml",
        )
        expect(result.returncode != 0, "unsupported report format must return a non-zero exit code", result)
        expect("unsupported bundle report format" in result.stdout, "report-format diagnostic disappeared", result)
        expect(not report.exists(), "unsupported report format wrote an output file", result)


def test_output_file_write_failure_exit_code() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-output-failure-") as directory:
        output_directory = Path(directory) / "existing-directory"
        output_directory.mkdir()
        result = run_cli(
            "--template",
            "Hello {{name}}",
            "--var",
            "name=MoonBit",
            "--output",
            str(output_directory),
        )
        expect(result.returncode != 0, "output write failure must return a non-zero exit code", result)
        expect("failed to write output file" in result.stdout, "output-write diagnostic disappeared", result)


def test_lint_failure_exit_code() -> None:
    result = run_cli("--template", "{{#open}}", "--lint")
    expect(result.returncode != 0, "lint errors must return a non-zero exit code", result)
    expect("MST-PARSE-003" in result.stdout, "stable parse diagnostic code disappeared", result)


def test_bundle_generation() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-") as directory:
        output = Path(directory)
        result = run_cli(
            "--bundle-manifest-file",
            "examples/bundle/manifest.json",
            "--bundle-profile",
            "dev",
            "--json-file",
            "examples/bundle/context.json",
            "--bundle-output-dir",
            str(output),
            "--bundle-validation-file",
            str(output / "validation.md"),
            "--bundle-plan-file",
            str(output / "plan.md"),
        )
        expect(result.returncode == 0, "bundle generation should succeed", result)
        expected_files = [
            output / ".env",
            output / "README.generated.md",
            output / "deploy" / "config.toml",
            output / "validation.md",
            output / "plan.md",
        ]
        for path in expected_files:
            expect(path.is_file(), f"bundle output was not created: {path.name}", result)
        expect("APP_PORT=3000" in (output / ".env").read_text(encoding="utf-8"), "dev profile was not applied", result)
        expect("validation errors: 0" in (output / "plan.md").read_text(encoding="utf-8"), "plan is not clean", result)


def write_manifest(directory: Path, files: list[dict[str, str]]) -> Path:
    manifest = directory / "manifest.json"
    manifest.write_text(
        json.dumps({"name": "cli-contract-test", "files": files}),
        encoding="utf-8",
    )
    return manifest


def test_bundle_check_only_writes_no_generated_files() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-check-") as directory:
        root = Path(directory)
        output = root / "generated"
        manifest = write_manifest(root, [{"path": "README.md", "template": "# checked"}])
        result = run_cli(
            "--bundle-manifest-file",
            str(manifest),
            "--bundle-output-dir",
            str(output),
            "--bundle-check-only",
        )
        expect(result.returncode == 0, "bundle check-only should succeed", result)
        expect("without writing generated files" in result.stdout, "check-only confirmation disappeared", result)
        expect(not output.exists(), "bundle check-only wrote generated files", result)


def test_bundle_parent_traversal_is_blocked() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-traversal-") as directory:
        root = Path(directory)
        output = root / "generated"
        escaped = root / "escape.txt"
        manifest = write_manifest(root, [{"path": "../escape.txt", "template": "blocked"}])
        result = run_cli(
            "--bundle-manifest-file",
            str(manifest),
            "--bundle-output-dir",
            str(output),
        )
        expect(result.returncode != 0, "parent traversal must return a non-zero exit code", result)
        expect("parent traversal" in result.stdout, "parent-traversal diagnostic disappeared", result)
        expect(not escaped.exists(), "parent traversal escaped the output directory", result)


def test_bundle_duplicate_paths_are_blocked() -> None:
    with tempfile.TemporaryDirectory(prefix="moon-mustache-cli-duplicate-") as directory:
        root = Path(directory)
        output = root / "generated"
        manifest = write_manifest(
            root,
            [
                {"path": "deploy\\config.toml", "template": "first"},
                {"path": "deploy/config.toml", "template": "second"},
            ],
        )
        result = run_cli(
            "--bundle-manifest-file",
            str(manifest),
            "--bundle-output-dir",
            str(output),
        )
        expect(result.returncode != 0, "duplicate output paths must return a non-zero exit code", result)
        expect("duplicate-output-path" in result.stdout, "duplicate-path diagnostic disappeared", result)
        expect(not output.exists(), "invalid duplicate-path bundle wrote files", result)


def main() -> int:
    parser = argparse.ArgumentParser(description="Black-box integration tests for the Moon Mustache CLI")
    parser.add_argument("--json-output", type=Path, help="optional path for a machine-readable result")
    args = parser.parse_args()

    tests = [
        ("inline render", test_inline_render),
        ("file-backed render", test_file_render),
        ("output file", test_output_file),
        ("strict failure exit code", test_strict_failure_exit_code),
        ("invalid JSON exit code", test_invalid_json_exit_code),
        ("missing partial exit code", test_missing_partial_exit_code),
        ("missing input file exit code", test_missing_input_file_exit_code),
        ("invalid bundle manifest exit code", test_invalid_bundle_manifest_exit_code),
        ("unsupported bundle report format exit code", test_unsupported_bundle_report_format_exit_code),
        ("output file write failure exit code", test_output_file_write_failure_exit_code),
        ("lint failure exit code", test_lint_failure_exit_code),
        ("bundle generation", test_bundle_generation),
        ("bundle check-only writes no generated files", test_bundle_check_only_writes_no_generated_files),
        ("bundle parent traversal is blocked", test_bundle_parent_traversal_is_blocked),
        ("bundle duplicate paths are blocked", test_bundle_duplicate_paths_are_blocked),
    ]
    results: list[dict[str, object]] = []
    try:
        for name, test in tests:
            result = case(name, test)
            results.append(result)
            print(f"PASS  {name} ({result['duration_ms']} ms)")
    except Exception as error:
        results.append({"name": name, "status": "failed", "error": str(error)})
        print(f"FAIL  {name}\n{error}", file=sys.stderr)
        status = 1
    else:
        status = 0

    payload = {
        "suite": "moon-mustache CLI integration",
        "passed": sum(item["status"] == "passed" for item in results),
        "total": len(tests),
        "cases": results,
    }
    if args.json_output:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"CLI integration: {payload['passed']} / {payload['total']} passed")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
