import { spawn } from 'node:child_process'

const port = 4277
const baseUrl = `http://127.0.0.1:${port}`

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function waitForHealth() {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    try {
      const response = await fetch(`${baseUrl}/api/health`)
      if (response.ok) {
        return
      }
    } catch (_) {
      // Server is still starting.
    }
    await sleep(500)
  }
  throw new Error('playground API did not become healthy in time')
}

async function verifyRender() {
  const response = await fetch(`${baseUrl}/api/render`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      template: '# {{project.name}}\n{{#features}}- {{.}}\n{{/features}}\n{{> footer}}',
      contextJson: JSON.stringify({
        project: { name: 'moon-mustache' },
        features: ['CLI rendering', 'Spec parity'],
      }),
      partialsJson: JSON.stringify({
        footer: 'Generated by {{project.name}}.',
      }),
      strictMissing: true,
    }),
  })
  if (!response.ok) {
    throw new Error(`render request failed with status ${response.status}`)
  }
  const payload = await response.json()
  if (payload.errors?.length) {
    throw new Error(`render diagnostics returned: ${payload.errors.join('; ')}`)
  }
  if (!payload.output.includes('moon-mustache') || !payload.output.includes('Generated by')) {
    throw new Error('render output did not contain expected content')
  }
}

const child = spawn(process.execPath, ['server.mjs'], {
  env: {
    ...process.env,
    PLAYGROUND_API_PORT: String(port),
  },
  stdio: 'inherit',
})

try {
  await waitForHealth()
  await verifyRender()
  console.log('playground smoke test passed')
} finally {
  child.kill()
}
