name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show MoonBit version
        run: moon version --all

      - name: Run moon check
        run: moon check

      - name: Run moon test
        run: moon test
